core_homepage:
    path:     /
    defaults:
        _controller: CoreBundle:Core:index

core_contact:
    path:     /contact
    defaults:
        _controller: CoreBundle:Core:contact

core_test:
    path: /test/{id}
    defaults:
        _controller: CoreBundle:Core:test
