# src/OC/PlatformBundle/Resources/config/routing.yml

hello_the_world:
    path:     /hello-world
    defaults: { _controller:OCPlatformBundle:Advert:index}

bye_bye_wolrd:
    path:     /bye-world
    defaults: { _controller:OCPlatformBundle:Advert:bye}
