# src/OC/PlatformBundle/Resources/config/routing.yml

# hello_the_world:
#     path:     /hello-world
#     defaults: { _controller:OCPlatformBundle:Advert:index}

# bye_bye_wolrd:
#     path:     /bye-world
#     defaults: { _controller:OCPlatformBundle:Advert:bye}

# oc_platform_view_slug:
#     path:            /platform/{year}/{slug}.{_format}
#     defaults:
#         _controller: OCPlatformBundle:Advert:viewSlug
#         format:      html
#     requirements:
#         year:        \d{4}
#         format:      html|xml

oc_platform_home:
    path:            /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page:        1
    requirements:
        page:        \d*


oc_platform_view:
    path:            /advert/{id}/{slug}
    defaults:
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id:          \d+


oc_platform_add:
    path:            /add
    defaults:
        _controller: OCPlatformBundle:Advert:add

oc_platform_edit:
    path:            /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id:          \d+

oc_platform_delete:
    path:            /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id:          \d+

oc_platform_json:
    path: /test/{json}
    defaults:
        _controller: OCPlatformBundle:Advert:ParamConverter
