services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - 50
        calls:
            - [ setLocale, ["%locale%"]]

    oc_platform.email.notification_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.notification_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist}

    # oc_platform.validator.antiflood:
    #     class: OC\PlatformBundle\Validator\AntifloodValidator
    #     arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
    #     tags:
    #         - {name: validator.constraint_validator, alias: oc_platform_antiflood}

    oc_platform.twig.antispam_extension:
        class: OC\PlatformBundle\Twig\AntispamExtension
        arguments:
            - "@oc_platform.antispam"
        tags:
            - { name: twig.extension }

    oc_platform.form.ckeditor:
        class: OC\PlatformBundle\Form\CkeditorType
        tags:
            - { name: form.type, alias: ckeditor}

    oc_platform.beta.html_adder:
        class: OC\PlatformBundle\Beta\BetaHTMLAdder

    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments:
            - "@oc_platform.beta.html_adder"
            - "2018-07-01"
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta}

    # oc_platform.bigbrother.message_notificator:
    #     class: OC\PlatformBundle\BigBrother\MessageNotificator
    #     arguments:
    #         - "@mailer"
    #
    # oc_platform.bigbrother.message_listener:
    #     class: OC\PlatformBundle\BigBrother\MessageListener
    #     arguments:
    #         - "oc_platform.bigbrother.message_notificator"
    #         - ["test"]
    #     tags:
    #         - { name: kernel.event_listener, event: oc_platform.post_message, method: processMessage }
