services:
#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam
        arguments:
            - "@mailer"
            - locale
            - 50

    oc_platform.email.notification_mailer:
        class: OC\PlatformBundle\Email\ApplicationMailer
        arguments:
            - "@mailer"

    oc_platform.doctrine_listener.application_creation:
        class: OC\PlatformBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - "@oc_platform.email.notification_mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist}

    oc_platform.validator.antiflood:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
        tags:
            - {name: validator.constraint_validator, alias: oc_platform_antiflood}
